# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import decisionmaking_pb2 as decisionmaking__pb2


class DecisionmakingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MakeSnapshot = channel.unary_unary(
                '/store.Decisionmaking/MakeSnapshot',
                request_serializer=decisionmaking__pb2.Snapshot.SerializeToString,
                response_deserializer=decisionmaking__pb2.Snapshot.FromString,
                )


class DecisionmakingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MakeSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DecisionmakingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MakeSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeSnapshot,
                    request_deserializer=decisionmaking__pb2.Snapshot.FromString,
                    response_serializer=decisionmaking__pb2.Snapshot.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'store.Decisionmaking', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Decisionmaking(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MakeSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/store.Decisionmaking/MakeSnapshot',
            decisionmaking__pb2.Snapshot.SerializeToString,
            decisionmaking__pb2.Snapshot.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
